name: flutter_gpu_point_cloud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  file_picker: ^10.2.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - shaders/
    - shorebird.yaml # - assets/shaders/
