name: flutter_gpu_point_cloud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  file_picker: ^6.1.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - shaders/ # assets/shaders/
    - shorebird.yaml
